queue_rules:
  - name: Run tests on main branch
    queue_conditions:
      - check-success = test
    batch_size: 2
    batch_max_wait_time: "30 seconds"
    merge_conditions:
      - check-success = lint
      - check-success = test

partition_rules:
  - name: frontend
    fallback_partition: false
    conditions:
      - files ~= frontend

  - name: backend
    fallback_partition: false
    conditions:
      - files ~= backend

pull_request_rules:
  - name: automatic merge
    conditions:
      - base=main
      - label!=manual merge
    actions:
      queue:
