priority_rules:
  - name: extended
    priority: high
    conditions:
      - base = main

queue_rules:
  - name: hotfix
    queue_branch_prefix: mergify/merge-queue/
    queue_conditions:
      - base=LTS/base-truc
    merge_conditions:
      - label=LTS/base-truc
      - check-success=kjlkjlkj
    speculative_checks: 1
  - name: master
    queue_branch_prefix: mergify/merge-queue/
    queue_conditions:
      - base=master
    merge_conditions:
      - label=master
      - check-success=kjlkjlkj
    speculative_checks: 1

pull_request_rules:
  - name: Assign t-shirt size to PR
    description: >-
      Assign a t-shirt size label to a pull request based on the number of lines
      changed.
    conditions:
      - '#modified-lines >= 100'
      - '#modified-lines < 500'
    actions:
      label:
        toggle:
          - size/L
  - name: Automatic merge
    description: Merge when PR passes all branch protection and has label automerge
    conditions:
      - label = automerge
    actions:
      merge: 
  - name: Ping PR author when conflicting
    description: Warn the pull request author when their PR are conflicting
    conditions:
      - conflict
      - '-closed'
    actions:
      comment:
        message: >
          👋 {{author}} your PR is conflicting and needs to be updated to be
          merged
