queue_rules:
  - name: Run tests on main branch
    queue_conditions:
      - check-success = test
    batch_size: 2
    batch_max_wait_time: "30 seconds"
    merge_conditions:
      - check-success = test
