queue_rules:
  - name: qsdqsd
    queue_conditions:
      - base=stage/v2025.2
    batch_size: 2
    batch_max_wait_time: "30 seconds"
    merge_conditions:
      - and:
          - check-success = placeholder_job
          - check-success = placeholder_job_2
          - check-success = placeholder_job_3
